### ISSUE TITLE
Build a hex file for upload from command line

### ISSUE THREAD

**Issue by mulderp** [Pinoccio/js-stk500#7]
Hi,

I was wondering what you think of adding some example, where a hex file would be built from the command line. This file could then be uploaded with js-stk500.

I wrote some thoughts on hex file compilation here: http://thinkingonthinking.com/an-arduino-sketch-from-scratch/

**Comment by jacobrosenthal** [comment]
Its a nice write up. Ive resisted makefile solutions in the past because
who knows what Arduino is going to do.

I really like leo, where adam is translating builds into javascript
https://www.npmjs.com/package/leo

But Im currently using arduino 1.6's command line functionality on a remote
build server:
https://registry.hub.docker.com/u/jacobrosenthal/arduino-server/

**Comment by soldair** [comment]
i have a module for pinoccio that builds the firmware using arduino on the command line pinoccio-arduino-compile (https://github.com/soldair/pinoccio-arduino-compile) and the pinoccio cli tool comes with a batch-flash command that helps flash the hex on many scouts at the same time

**Comment by mulderp** [comment]
Thanks for the feedback. These are all nice options to explore!
I'll close this issue for now, part of the discussion is moved to https://github.com/AdamMagaluk/leo/issues/29

I guess one of the difficulties is indeed that the Arduino IDE keeps changing paths of libraries. Maybe it would be a valid option to fetch the Arduino libraries into the local project.
